name: WaCo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/wacologo.png
    - assets/images/WaCo Dine In Image.png
    - assets/images/WaCo Take out Image.png
    - assets/images/Milktea-removebg-preview.png
    - assets/images/Iced-Coffee_img-removebg-preview.png
    - assets/images/FruitSOda-removebg-preview.png
    - assets/images/Waffle Oreo.png
    - assets/images/Fruit_yogurt-removebg-preview.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/wacologo.png"
